# CMake generated Testfile for 
# Source directory: /home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/download_urdf/urdfdom/urdf_parser/test
# Build directory: /home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/build_urdfdom/urdf_parser/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(urdf_double_convert "/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/build_urdfdom/bin/Debug/urdf_double_convert" "--gtest_output=xml:/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/build_urdfdom/test_results/urdf_double_convert.xml")
  set_tests_properties(urdf_double_convert PROPERTIES  ENVIRONMENT "LC_ALL=C" TIMEOUT "240" _BACKTRACE_TRIPLES "/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/download_urdf/urdfdom/urdf_parser/test/CMakeLists.txt;38;add_test;/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/download_urdf/urdfdom/urdf_parser/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(urdf_double_convert "/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/build_urdfdom/bin/Release/urdf_double_convert" "--gtest_output=xml:/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/build_urdfdom/test_results/urdf_double_convert.xml")
  set_tests_properties(urdf_double_convert PROPERTIES  ENVIRONMENT "LC_ALL=C" TIMEOUT "240" _BACKTRACE_TRIPLES "/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/download_urdf/urdfdom/urdf_parser/test/CMakeLists.txt;38;add_test;/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/download_urdf/urdfdom/urdf_parser/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(urdf_double_convert "/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/build_urdfdom/bin/RelWithDebInfo/urdf_double_convert" "--gtest_output=xml:/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/build_urdfdom/test_results/urdf_double_convert.xml")
  set_tests_properties(urdf_double_convert PROPERTIES  ENVIRONMENT "LC_ALL=C" TIMEOUT "240" _BACKTRACE_TRIPLES "/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/download_urdf/urdfdom/urdf_parser/test/CMakeLists.txt;38;add_test;/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/download_urdf/urdfdom/urdf_parser/test/CMakeLists.txt;0;")
else()
  add_test(urdf_double_convert NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(urdf_double_convert_locale "/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/build_urdfdom/bin/Debug/urdf_double_convert" "--gtest_output=xml:/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/build_urdfdom/test_results/urdf_double_convert_locale.xml")
  set_tests_properties(urdf_double_convert_locale PROPERTIES  ENVIRONMENT "LC_ALL=nl_NL.UTF-8" TIMEOUT "240" _BACKTRACE_TRIPLES "/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/download_urdf/urdfdom/urdf_parser/test/CMakeLists.txt;44;add_test;/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/download_urdf/urdfdom/urdf_parser/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(urdf_double_convert_locale "/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/build_urdfdom/bin/Release/urdf_double_convert" "--gtest_output=xml:/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/build_urdfdom/test_results/urdf_double_convert_locale.xml")
  set_tests_properties(urdf_double_convert_locale PROPERTIES  ENVIRONMENT "LC_ALL=nl_NL.UTF-8" TIMEOUT "240" _BACKTRACE_TRIPLES "/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/download_urdf/urdfdom/urdf_parser/test/CMakeLists.txt;44;add_test;/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/download_urdf/urdfdom/urdf_parser/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(urdf_double_convert_locale "/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/build_urdfdom/bin/RelWithDebInfo/urdf_double_convert" "--gtest_output=xml:/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/build_urdfdom/test_results/urdf_double_convert_locale.xml")
  set_tests_properties(urdf_double_convert_locale PROPERTIES  ENVIRONMENT "LC_ALL=nl_NL.UTF-8" TIMEOUT "240" _BACKTRACE_TRIPLES "/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/download_urdf/urdfdom/urdf_parser/test/CMakeLists.txt;44;add_test;/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/download_urdf/urdfdom/urdf_parser/test/CMakeLists.txt;0;")
else()
  add_test(urdf_double_convert_locale NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(urdf_unit_test "/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/build_urdfdom/bin/Debug/urdf_unit_test" "--gtest_output=xml:/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/build_urdfdom/test_results/urdf_unit_test.xml")
  set_tests_properties(urdf_unit_test PROPERTIES  ENVIRONMENT "LC_ALL=C" TIMEOUT "240" _BACKTRACE_TRIPLES "/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/download_urdf/urdfdom/urdf_parser/test/CMakeLists.txt;38;add_test;/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/download_urdf/urdfdom/urdf_parser/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(urdf_unit_test "/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/build_urdfdom/bin/Release/urdf_unit_test" "--gtest_output=xml:/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/build_urdfdom/test_results/urdf_unit_test.xml")
  set_tests_properties(urdf_unit_test PROPERTIES  ENVIRONMENT "LC_ALL=C" TIMEOUT "240" _BACKTRACE_TRIPLES "/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/download_urdf/urdfdom/urdf_parser/test/CMakeLists.txt;38;add_test;/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/download_urdf/urdfdom/urdf_parser/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(urdf_unit_test "/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/build_urdfdom/bin/RelWithDebInfo/urdf_unit_test" "--gtest_output=xml:/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/build_urdfdom/test_results/urdf_unit_test.xml")
  set_tests_properties(urdf_unit_test PROPERTIES  ENVIRONMENT "LC_ALL=C" TIMEOUT "240" _BACKTRACE_TRIPLES "/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/download_urdf/urdfdom/urdf_parser/test/CMakeLists.txt;38;add_test;/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/download_urdf/urdfdom/urdf_parser/test/CMakeLists.txt;0;")
else()
  add_test(urdf_unit_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(urdf_unit_test_locale "/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/build_urdfdom/bin/Debug/urdf_unit_test" "--gtest_output=xml:/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/build_urdfdom/test_results/urdf_unit_test_locale.xml")
  set_tests_properties(urdf_unit_test_locale PROPERTIES  ENVIRONMENT "LC_ALL=nl_NL.UTF-8" TIMEOUT "240" _BACKTRACE_TRIPLES "/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/download_urdf/urdfdom/urdf_parser/test/CMakeLists.txt;44;add_test;/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/download_urdf/urdfdom/urdf_parser/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(urdf_unit_test_locale "/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/build_urdfdom/bin/Release/urdf_unit_test" "--gtest_output=xml:/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/build_urdfdom/test_results/urdf_unit_test_locale.xml")
  set_tests_properties(urdf_unit_test_locale PROPERTIES  ENVIRONMENT "LC_ALL=nl_NL.UTF-8" TIMEOUT "240" _BACKTRACE_TRIPLES "/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/download_urdf/urdfdom/urdf_parser/test/CMakeLists.txt;44;add_test;/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/download_urdf/urdfdom/urdf_parser/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(urdf_unit_test_locale "/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/build_urdfdom/bin/RelWithDebInfo/urdf_unit_test" "--gtest_output=xml:/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/build_urdfdom/test_results/urdf_unit_test_locale.xml")
  set_tests_properties(urdf_unit_test_locale PROPERTIES  ENVIRONMENT "LC_ALL=nl_NL.UTF-8" TIMEOUT "240" _BACKTRACE_TRIPLES "/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/download_urdf/urdfdom/urdf_parser/test/CMakeLists.txt;44;add_test;/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/download_urdf/urdfdom/urdf_parser/test/CMakeLists.txt;0;")
else()
  add_test(urdf_unit_test_locale NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(urdf_version_test "/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/build_urdfdom/bin/Debug/urdf_version_test" "--gtest_output=xml:/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/build_urdfdom/test_results/urdf_version_test.xml")
  set_tests_properties(urdf_version_test PROPERTIES  ENVIRONMENT "LC_ALL=C" TIMEOUT "240" _BACKTRACE_TRIPLES "/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/download_urdf/urdfdom/urdf_parser/test/CMakeLists.txt;38;add_test;/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/download_urdf/urdfdom/urdf_parser/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(urdf_version_test "/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/build_urdfdom/bin/Release/urdf_version_test" "--gtest_output=xml:/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/build_urdfdom/test_results/urdf_version_test.xml")
  set_tests_properties(urdf_version_test PROPERTIES  ENVIRONMENT "LC_ALL=C" TIMEOUT "240" _BACKTRACE_TRIPLES "/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/download_urdf/urdfdom/urdf_parser/test/CMakeLists.txt;38;add_test;/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/download_urdf/urdfdom/urdf_parser/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(urdf_version_test "/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/build_urdfdom/bin/RelWithDebInfo/urdf_version_test" "--gtest_output=xml:/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/build_urdfdom/test_results/urdf_version_test.xml")
  set_tests_properties(urdf_version_test PROPERTIES  ENVIRONMENT "LC_ALL=C" TIMEOUT "240" _BACKTRACE_TRIPLES "/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/download_urdf/urdfdom/urdf_parser/test/CMakeLists.txt;38;add_test;/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/download_urdf/urdfdom/urdf_parser/test/CMakeLists.txt;0;")
else()
  add_test(urdf_version_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(urdf_version_test_locale "/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/build_urdfdom/bin/Debug/urdf_version_test" "--gtest_output=xml:/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/build_urdfdom/test_results/urdf_version_test_locale.xml")
  set_tests_properties(urdf_version_test_locale PROPERTIES  ENVIRONMENT "LC_ALL=nl_NL.UTF-8" TIMEOUT "240" _BACKTRACE_TRIPLES "/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/download_urdf/urdfdom/urdf_parser/test/CMakeLists.txt;44;add_test;/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/download_urdf/urdfdom/urdf_parser/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(urdf_version_test_locale "/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/build_urdfdom/bin/Release/urdf_version_test" "--gtest_output=xml:/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/build_urdfdom/test_results/urdf_version_test_locale.xml")
  set_tests_properties(urdf_version_test_locale PROPERTIES  ENVIRONMENT "LC_ALL=nl_NL.UTF-8" TIMEOUT "240" _BACKTRACE_TRIPLES "/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/download_urdf/urdfdom/urdf_parser/test/CMakeLists.txt;44;add_test;/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/download_urdf/urdfdom/urdf_parser/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(urdf_version_test_locale "/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/build_urdfdom/bin/RelWithDebInfo/urdf_version_test" "--gtest_output=xml:/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/build_urdfdom/test_results/urdf_version_test_locale.xml")
  set_tests_properties(urdf_version_test_locale PROPERTIES  ENVIRONMENT "LC_ALL=nl_NL.UTF-8" TIMEOUT "240" _BACKTRACE_TRIPLES "/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/download_urdf/urdfdom/urdf_parser/test/CMakeLists.txt;44;add_test;/home/josh/wheel_limb_robotics/simulation/chrono/chrono/contrib/build-scripts/urdf/download_urdf/urdfdom/urdf_parser/test/CMakeLists.txt;0;")
else()
  add_test(urdf_version_test_locale NOT_AVAILABLE)
endif()
